###############################################################
#  Makefile     Compilation file.                             #
#                                                             #
#  September 2014                                             #
###############################################################/


CC	= gcc
CFLAGS	= -Wall -O3 

all:			sld.c
			$(CC) sld.c $(CFLAGS) -o sld.o

clean:			
			rm -f sld.o


